pull_request_rules:
  - name: Merge approved, passed PRs
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label=waiting-for-review
      - label!=no-merge
      - label!=wip
      - base=master
    actions:
      merge:
        method: merge
        strict: smart
      delete_head_branch: {}
