language: minimal
branches:
  only:
    - master

matrix:
  fast_finish: true

  include:
    - name: Test
      script: echo hello

    - name: Blah
      if: branch =~ ^blah-
      script: echo blah
