language: minimal
branches:
  only:
    - master
    - /^blah-v/

matrix:
  fast_finish: true

  include:
    - name: Test
      script: echo hello

    - name: Blah
      stage: release
      if: branch = master AND tag =~ ^blah-v
      script: echo blah
