language: minimal
branches:
  only:
    - master
    # Need to specify tags here, as branch safelists disable tag-based builds
    - /^blah-v/

matrix:
  fast_finish: true

  include:
    - name: Test
      script:
        - COMMITS="$(git log --pretty=oneline --abbrev-commit origin/master...HEAD)"
        - echo "${COMMITS}"
        - if [[ "${COMMITS}" == *"[asdasd]"* ]]; then echo nothing; exit 0; fi
        - echo hello

    - name: Bye
      script: echo bye

    - name: asdasd
      language: python
      dist: xenial
      python: 3.7
      script:
        - pip freeze

    - name: Blah
      stage: release
      # To skip the job altogether (non-trivial VM spin-up cost)
      if: tag =~ ^blah-v
      script: echo blah
      deploy:
        provider: script
        script: bash echo yo
        # By default only deploys on master branches, this enables tag releases
        on:
          tags: true
