name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: env | grep GITHUB_
      - run: |
          export ASD="asd
          zxc
          123"

          echo $ASD
          echo "$ASD"
