name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  asd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: [1, 0, 0, 0]
    steps:
      - run: echo ${{ matrix.x }}
      - run: exit ${{ matrix.x }}

  zxc:
    runs-on: ubuntu-latest
    if: always()
    needs: asd
    steps:
      - run: echo ${{ needs.asd }}
